services:
  server1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    command: node server1.js

  server2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    command: node server2.js

  nginx:
    image: nginx:latest
    container_name: my-nginx
    # Пробрасываем порт 80 контейнера -> 8080 хоста
    ports:
      - "8080:80"
    # Подключаем локальный nginx.conf в контейнер
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Заводим зависимость, чтобы Node сначала запустился
    depends_on:
      - server1
      - server2
